# Generated by Django 6.0.4 on 2026-04-25 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medecins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('medecins', models.ManyToManyField(blank=True, related_name='patients', to='medecins.medecin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_prise', models.TimeField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_prescription', models.DateField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medecins.medecin')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medecins.medicament')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationPrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confirmation', models.DateField(auto_now_add=True)),
                ('heure_confirmation', models.TimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='patients.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'date_confirmation')},
            },
        ),
    ]
